### ISSUE TITLE
Introduce a flag to perform a plan on all subdirectories

### ISSUE THREAD

**Issue by motatoes** [diggerhq/digger#133]
Request from @Derek. Given the following configuration:

```
── root
│   └── common
│   └── project
│       └── digger-test
│           ├── configuration.tf
│           └── gcs.tf
│       └── digger-test2
│           ├── configuration.tf
│           └── gcs.tf
│       └── digger-test3
│           ├── configuration.tf
│           └── gcs.tf
```

User wishes to run a terraform plan from every subdirectory within the `project` folder. Each directory in project has its own isolated state and therefore it can be ran independently. Every pull request with a change in any subdirectory should trigger terraform plans in the context of changed subdirectories. Terraform for any In additional there can be hundreds of folders each defining isolated resources. User does not want to define this for every single directory. 

Considerations: 

- Need a way to also trigger changes from folders which are common modules but defined outside of the directory. Should these trigger plans for *all* subdirectories? 
- Need a way to exclude some folders within `project` via some wildcard pattern

**Comment by derek10cloud** [comment]
> 

Thank you for your good suggestion @veziak. 
But placing `digger.yml` in each sub directory would be tiresome. 
As you may know that atlantis which could be an alternative tool for running terraform command can track all sub directories which there was a change when I make a PR.
Is there any way to track all changes in each sub directory?. I prefer to use digger than atlantis, because I don't have to set up machine for terraform ci when I make a PR.

**Comment by Spartakovic** [comment]
https://github.com/diggerhq/digger/pull/147
