### ISSUE TITLE
Golang Dependency Cache Miss on failed build/runs

### ISSUE THREAD

**Issue by ben-of-codecraft** [diggerhq/digger#1719]
### Feature

When testing against non versioned instances of Digger (branch, ref, tag) since the build and run happen in the same step golang dependencies are not cached, if there is an error. 

### Expected Behavior
* External dependencies will cache even if the run fails.  This makes subsequent runs testing specific feature faster build times. 

### Proposal
1. Download external go modules before build on cache-miss
2. Cache modules 
3. Do build and run as normal.

**Comment by BadakalaYashwanth** [comment]
@ben-of-codecraft Problem: 
When running tests on non-versioned instances of Digger (such as using branches, refs, or tags), Go dependencies are not cached if the build fails, causing delays in future builds.
Expected Behavior: Even if the build/run fails, Go module dependencies should be cached for faster subsequent builds.
Proposal: Modify the build process to ensure Go modules are downloaded and cached before the build starts.

Example for GitHub Actions (.github/workflows/main.yml):
steps:
- name: Cache Go modules
  uses: actions/cache@v2
  with:
    path: |
      ~/.cache/go-build
      ~/go/pkg/mod
    key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
    restore-keys: |
      ${{ runner.os }}-go-

- name: Download Go dependencies
  run: go mod download

**Comment by ben-of-codecraft** [comment]
Solved by #1750 
closing issue
