### ISSUE TITLE
any way to use terragrunt run-all?

### ISSUE THREAD

**Issue by noxjonas** [diggerhq/digger#474]
it appears that digger plan/apply merely runs `terragrunt plan/apply` when set up to use terragrunt. Is it possible to override this to use run-all instead?

**Comment by motatoes** [comment]
Hey @noxjonas unfortunately there is no way to do run-all with digger at the moment since we only support terragrunt on a project level, rather than running terragrunt with something like run-all or apply-all. The assumption would be that you create a digger project for every terragrunt.hcl file. 

Happy to discuss an extension to this if you have a usecase which needs usage of run-all!

**Comment by noxjonas** [comment]
Thanks for the quick reply! I'm still evaluating whether digger will suit my CICD needs.

Admittedly, terragrunt themselves don't think that run-all should be used for CI/CD, but I was hoping to use their dependency matrix between modules at least to run plans. And digger to get these plans in PR. 

One issue in the absence of support for run-all is I'd need to manually generate >30 projects. I guess it will be addressed with https://github.com/diggerhq/digger/issues/424

still trying to figure out how to make extra_args work for terragrunt though, so it's still very much work in progress...

**Comment by motatoes** [comment]
hey @noxjonas this is now supported and here are the docs page for it: https://docs.digger.dev/configuration/terragrunt-project-generation

Please give it a shot and let us know if that addresses it for you!
